### ISSUE TITLE
composer minimum-stability setting

### ISSUE THREAD

**Issue by robertogallea** [molteber/puz-dynamic-mail#7]
Why does the package require dev minimum-stability settings for composer? Is it strictly required?

Thank you.

**Comment by molteber** [comment]
It is because I haven't published it fully yet.
Haven't been able to work on this for a while because I'm currently on a 3 month exploration, whiteout my computer.

If you do try out the package, I will also suggest the `"prefer-stable": true` option to

**Comment by molteber** [comment]
It should also be considered unstable because I might make some breaking changes when I finalize the package for version 1.0.

**Comment by robertogallea** [comment]
Ok, thank you for your reply. However I tried it using Laravel 5.4 without success.

$config = array(
                'host' => $o->mail_host,
                'port' => $o->mail_port,
                'from' => array('address' => $o->mail_from_address, 'name' => $o->mail_from_name),
                'encryption' => null,
                'username' => $o->mail_username,
                'password' => $o->mail_password,
            );
            Mail::withConfig('smtp', $config)->to($user->email)->send($email);

Exception:  ReflectionException
Class mailer does not exist

Did I miss anything?

Thank you again.

**Comment by molteber** [comment]
Hmm, looks correct

I also remember this error occured some times when I was trying it out.
Unfortunately I don't remember if I resolved it or had to let it be until I got back home again.

**Comment by robertogallea** [comment]
Don't worry, it is not urgent. I hope you can manage to fix it once you get back home again.

Thanks.

**Comment by molteber** [comment]
I might be able to work something out by July-august. I'll notify you thru
this issue when I've worked something out

**Comment by molteber** [comment]
Hello @robertogallea.
You should check out the new updates now.
Have also made a release so you should need to set minimum-stability setting now.
I did not have any problems by adding it now so i believe it should work for you too then.

Note it's still in "beta", so can't say for sure about the stability, but it seems to be working fine for now.
I don't think i will be doing too much on this package for now but i will be using it for my own projects later on this year so it might get some updates if i find something bug-ish. Happy emailing!

**Comment by robertogallea** [comment]
Hi, 
Thank you for the update. I already found a solution for dynamic mail settings, but I will adopt your package anyway, since it is cleaner.  I will notice you if I found any issue. 

Thank you again!

**Comment by robertogallea** [comment]
Just gave a try. It seems to work perfectly. Good job!
