### ISSUE TITLE
Does this able to send using Queue?

### ISSUE THREAD

**Issue by ssatz** [molteber/puz-dynamic-mail#8]
Is it possible to queue a mail?

**Comment by molteber** [comment]
I haven't thought of that actually. 
You can give it a shot, but I will check it out and see what I can do if not

**Comment by ssatz** [comment]
Queues are not working!

**Comment by molteber** [comment]
That is no good! I will have to take a look at it over the weekend. I'll keep you posted!

**Comment by molteber** [comment]
I haven't found a good solution to this yet. I'll give it some more shots and see what i find

**Comment by molteber** [comment]
@ssatz after some more trying and failing, the solution I can suggest is to add email config to an job which sends the email directly without queuing it.
So to enforce a solution like that, make sure you remove Queable trait etc from the mailables, just in case

**Comment by ssatz** [comment]
@molteber  :+1: Thanks for the update & noted !
